### ISSUE TITLE
More instruction for preparing Ego4D dataset

### ISSUE THREAD

**Issue by Kami-code** [Sid2697/HOI-Ref#2]
Hi @Sid2697 ,

Thanks for producing such an insightful and useful project! I am trying to reproduce the model myself. While preparing EPIC-Kitchen is not very hard, preparing Ego4D is much more difficult for me cause of its huge capacity and different subsets. Can you provide a detailed instruction for preparing Ego4D dataset? Which part of it should I download? Shall I extract the frames myself? Is there any script to do that? 

Best Regards.

**Comment by Sid2697** [comment]
Hello @Kami-code ,

Thank you for your interest in our work!
> Which part of it should I download?

We have used the hand and objects subset of the Ego4D dataset.

> Shall I extract the frames myself? Is there any script to do that?

Yes, you'll have to extract the frames yourself.

Additional tip:
The naming of the images in the dataset can provide you the video id and the frame number to use. For example, one of the path in test data for Ego4D is `Ego4D/v2/frames/9267f964-d5a1-4062-872f-657e2a4cbe81/frame_0000090023.jpg` here `9267f964-d5a1-4062-872f-657e2a4cbe81` is the clip id and `frame_0000090023` is the frame number. We have also provided `ego4d-clip-ids.json` that has clip ids of the videos from Ego4D used in the HOI-QA dataset (documented [here](https://github.com/Sid2697/HOI-Ref/blob/main/hoiqa_dataset/HOIQA_README.md)).

I hope this makes things easy, let me know if you have more doubts.

Regards,
Siddhant Bansal

**Comment by Kami-code** [comment]
Hi @Sid2697 , 

Thanks for your detailed answer. There is only one question left for me: What are the frame extraction configurations when you are extracting the frames? Do you have a specific configuration like "ffmpeg -i $f -vf "scale=-1:256,fps=30" -qscale:v 2  frames/$frame_%010d.jpg"?

**Comment by Sid2697** [comment]
Hello @Kami-code ,

I have extracted the frames using CV2. The following are the two lines that help me grab a particular frame. `frame_count` is the frame number that we are interested in. I have extracted all the frames for a given clip in Ego4D.

`video.set(cv2.CAP_PROP_POS_FRAMES, frame_count)`
`success, frame = video.read()`

Let me know if additional details are required.

**Comment by Kami-code** [comment]
Thanks for your help @Sid2697 . I will try your pipeline as soon as possible. 

Best wishes.
